#  Ex Vivo Human Model for Assessing Immunotoxicity of Per- and Polyfluoroalkyl Substances (PFAS)
## Authors
Allison Loan, Lauren M. Bradford, Andrée Nunnikhoven, Gong Zhang, Emily Dupuis, Eunnara Cho, Matthew J. Meier, Rocio Aranda-Rodriguez,  Azam Tayabali, Kristin M. Eccles, David Prescott

## Abstract
Immunotoxicity has emerged as a key health concern for per- and polyfluoroalkyl substances (PFAS), with numerous animal studies showing reduced T-dependent antibody responses (TDAR) and some human epidemiological studies reporting decreased vaccine antibody titers. In recent years, many PFAS have been heavily regulated in Canada; however, with more than 14,000 PFAS and their well-known environmental persistence, evaluating immunotoxicity for each chemical is critical but impractical. This highlights the need for efficient, human-relevant test systems. Here, we assessed immunomodulatory effects of six PFAS analogues using an ex vivo human peripheral blood mononuclear cell (PBMC) model. PBMCs were pre-exposed to PFAS prior to stimulation to mimic environmentally relevant exposure scenarios, in which PFAS exposure precedes an immune challenge. Two immune stimuli were applied, including lipopolysaccharide (LPS) to trigger innate responses and phytohemagglutinin (PHA) to activate T-cell-mediated adaptive pathways. Multiple endpoints were assessed, including cytokine secretion, T-cell proliferation, and transcriptomic alterations. This study found that several PFAS analogues suppressed cytokine secretion and altered T-cell proliferation to varying degrees following PHA activation. Transcriptomics results suggest decreased B-cell identity and immunoglobulin gene expression and increased expression of genes related to T-cell activation and proliferation. Overall, the human PBMC model proved to be a cost-effective, ethical, and sensitive new approach method (NAM) that aligned well with prior in vivo data.

## Processing Notebooks
All data processing, cleaning, and preprocessing notebooks are located in the Processing_Notebooks folder
